forge 'https://forge.puppet.com'

# Modules from the Puppet Forge
mod 'puppetlabs-stdlib', '6.1.0'
mod 'WhatsARanjit-node_manager', '0.7.2'
mod 'puppetlabs-apply_helpers', '0.1.0'
mod 'puppetlabs-bolt_shim', '0.3.0'


# Modules from Git
mod 'puppetlabs-peadm',
    git: 'https://github.com/puppetlabs/puppetlabs-peadm.git',
    ref: 'master'
